export const COLORS = {
  // GERAL
  fundoPrincipal: '#F7F7FB',
  // CADASTRO E LOGIN
  loginTitulo: '#595D7C',
  loginFundo: '#EFEFF5',
  loginEsqueciSenha: '#A31414',
  loginLinks: '#595D7CB0',
  recuperarSenhaBordaCaixa: '#E6BAD1',
  cadTitulo: '#595D7C',
  cadFundo: '#F7F7FB',
  cadBotao: '#595D7C',
  cadBotaoTexto: '#FFFFFF',
  cadTextInputFundo: '#FFFFFF',
  cadTextInputTexto: '#000000',
  cadModalContainerFundo: '#FFFFFF',
  cadModalCarregando: '#a31414',
  cadModalFecharTexto: '#a31414',
  cadModalSeparadorItens: '#ECECEC',
  cadModalItemTexto: '#111111',
  cadModalAvisoTexto: '#666666',
  cadCaixaPreferenciasBorda: '#B6ACEA',
  cadCaixaPreferenciasFundo: '#F2F1F8',
  cadCaixaPreferenciasSombra: '#8B86B8',
  cadTextoAdicionarLimites: '#EF596D',
  cadCheckboxFundo: '#AFA1E8',
  cadCheckboxTexto: '#111111',
  cadCheckboxLink: '#F07D86',
  questionarioCaixaBorda: '#B6ACEA',
  questionarioCaixaFundo: '#F2F1F8',
  questionarioCaixaSombra: '#8B86B8',
  questionarioCaixaTexto: '#595D7C',
  questionarioTextInputFundo: '#FFFFFF',
  questionarioTextInputTexto: '#000000',
  questionarioTextInputBorda: '#D7D2F0',
  questionarioOpcaoFundo: '#FFFFFF',
  questionarioOpcaoBorda: '#D5CFF0',
  questionarioOpcaoTexto: '#595D7C',
  questionarioOpcaoFundoSelecionada: '#AFA1E8',
  questionarioOpcaoBordaSelecionada: '#AFA1E8',
  questionarioOpcaoTextoSelecionada: '#FFFFFF',
  // SPLASH
  splashFundo: '#F7F7FB',
  // TELA DASHBOARD
  dashboardChipMesTexto: '#FFFFFF',
  dashboardChipMesFundo: '#D4AFCA',
  dashboardIconeBotaoCanto: '#595D7C',
  dashboardHeaderFundo: '#F7F7FB',
  dashboardHeaderBorda: '#E3DFF891',
  // HISTÓRICO DE CHAT
  histChatBotao3Pontos: '#6D74A8',
  histChatBotao3PontosFundo: '#EEF1FF',
  histChatBotao3PontosBorda: 'rgba(131, 111, 226, 0.35)',
  histChatTextInputFundo: '#FFFFFF',
  histChatTextInputTexto: '#000000',
  histChatTextInputBorda: 'rgba(131, 111, 226, 0.2)',
  // CHAT
  chatFundo: '#EFF2FF',
  chatHeaderFundo: '#FFFFFF',
  chatHeaderBorda: 'rgba(131, 111, 226, 0.16)',
  chatDestinatarioNome: '#4652A4',
  chatDestinatarioStatus: '#7D84B3',
  chatIconeRobo: '#4652A4',
  chatIconeRoboFundo: '#EEF1FF',
  chatIconeRoboBorda: 'rgba(131, 111, 226, 0.35)',
  chatBotao3Pontos: '#6D74A8',
  chatBotao3PontosFundo: '#F5F6FF',
  chatBotoesAdicionaisEnviar: '#5F68A0',
  chatBotoesAdicionaisEnviarFundo: '#F7F8FF',
  chatBotaoEnviar: '#FFFFFF',
  chatBotaoEnviarFundo: '#4652A4',
  chatDestinatarioMensagemFundo: '#FFFFFF',
  chatDestinatarioMensagemTexto: '#2F356B',
  chatDestinatarioMensagemBorda: 'rgba(131, 111, 226, 0.25)',
  chatRemetenteMensagemFundo: '#4652A4',
  chatRemetenteMensagemTexto: '#FFFFFF',
  chatRemetenteMensagemBorda: '#4652A4',
  chatContainerEnviarFundo: '#FFFFFF',
  chatContainerEnviarBorda: 'rgba(131, 111, 226, 0.2)',
  chatContainerEnviarSombra: '#1E245A',
  chatTextInputFundo: '#FFFFFF',
  chatTextInputTexto: '#000000',
  chatTextInputBorda: 'rgba(131, 111, 226, 0.2)',
};
