import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1 },
  content: { padding: 16, paddingBottom: 120 },
  heroCard: { padding: 16, alignItems: 'center' },
  heroTitle: { fontSize: 20, fontWeight: '700', color: '#FFF' },
  heroSubtitle: { fontSize: 13, color: '#EEE', marginTop: 6 },
  sectionsWrap: { marginTop: 12 },
  sectionCard: { marginBottom: 12 },
  loadingWrap: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  itemRow: { marginBottom: 10, borderBottomWidth: 1, borderBottomColor: '#eee', paddingBottom: 8 },
  itemInput: { marginBottom: 8 },
  selectCategoria: { padding: 10, backgroundColor: '#f3f3f3', borderRadius: 8, marginBottom: 8 },
  selectCategoriaText: { color: '#333' },
  removeItemButton: { alignSelf: 'flex-end', paddingVertical: 6, paddingHorizontal: 10 },
  removeItemText: { color: '#c00' },
  addItemButton: { padding: 10, alignItems: 'center' },
  addItemText: { color: '#1B2046', fontWeight: '600' },
  actionsRow: { marginTop: 12, alignItems: 'center' },
  saveButton: { width: '100%' },
  pressableFecharModal: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'center', alignItems: 'center' },
  modalContainer: { width: '90%', maxHeight: '80%', backgroundColor: '#fff', borderRadius: 8, padding: 12 },
  questionTitle: { fontSize: 16, fontWeight: '700', marginBottom: 8 },
  categoriaNomeTouchable: { paddingVertical: 10 },
  categoriaNome: { fontSize: 15 },
  textoFecharModalTouchable: { marginTop: 12, alignItems: 'center' },
  textoFecharModal: { color: '#007AFF' },
});
