import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.splashFundo,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  cornerTopLeft: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 0,
    height: 0,
    borderTopWidth: 230,
    borderRightWidth: 230,
    borderTopColor: COLORS.dadoDois,
    borderRightColor: 'transparent',
  },
  cornerTopRight: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 0,
    height: 0,
    borderTopWidth: 195,
    borderLeftWidth: 195,
    borderTopColor: COLORS.dadoUm,
    borderLeftColor: 'transparent',
  },
  cornerBottomLeft: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: 0,
    height: 0,
    borderBottomWidth: 240,
    borderRightWidth: 240,
    borderBottomColor: COLORS.dadoUm,
    borderRightColor: 'transparent',
  },
  cornerBottomRight: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 0,
    height: 0,
    borderBottomWidth: 210,
    borderLeftWidth: 210,
    borderBottomColor: COLORS.dadoDois,
    borderLeftColor: 'transparent',
  },
  diagonalBandTop: {
    position: 'absolute',
    top: 0,
    left: '-14%',
    width: '128%',
    height: 108,
    backgroundColor: COLORS.fundoPrincipal,
    transform: [{ rotate: '-33deg' }, { translateY: 136 }],
  },
  diagonalBandBottom: {
    position: 'absolute',
    bottom: 0,
    left: '-14%',
    width: '128%',
    height: 108,
    backgroundColor: COLORS.fundoPrincipal,
    transform: [{ rotate: '-33deg' }, { translateY: -136 }],
  },
  logoGlow: {
    position: 'absolute',
    width: 360,
    height: 360,
    borderRadius: 180,
    backgroundColor: 'rgba(255, 255, 255, 0.28)',
    shadowColor: COLORS.dadoDois,
    shadowOpacity: 0.18,
    shadowRadius: 34,
    shadowOffset: { width: 0, height: 14 },
  },
  logoWrap: {
    width: 300,
    height: 300,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: {
    width: 260,
    height: 260,
  },
});
