import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.cadFundo,
    paddingTop: -50,
  },
  contentContainer: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    paddingBottom: 40,
  },
  containerScroll: {
    flex: 1,
    width: '96%',
    alignSelf: 'center',
    backgroundColor: COLORS.cadFundo,
  },
  overlay: {
    width: '85%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
  },
  borderOverlay: {
    borderWidth: 1,
    borderRadius: 12,
    borderColor: COLORS.cadCaixaPreferenciasBorda,
    width: '95%',
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: 'transparent',
  },
  logo: {
    width: 140,
    height: 140,
  },
  stepTwoContainer: {
    alignItems: 'center',
    paddingVertical: 30,
    justifyContent: 'center',
    flexGrow: 1,
  },
  titulo: {
    fontFamily: 'SugoDisplay',
    fontSize: 52,
    color: COLORS.cadTitulo,
    marginBottom: 10,
  },
  segmentAction: {
    marginTop: 16,
    marginBottom: 16,
  },
  segmentActionText: {
    color: COLORS.cadTextoAdicionarLimites,
    fontSize: 15,
    textAlign: 'center',
  },
  stepTwoErrorText: {
    width: '95%',
    color: COLORS.loginEsqueciSenha,
    fontSize: 13,
    marginTop: 8,
    textAlign: 'left',
  },
  stepTwoHelperText: {
    color: '#7A6E78',
    fontSize: 11.5,
    lineHeight: 16,
    marginTop: -1,
    marginBottom: 10,
    paddingHorizontal: 5,
  },
  questionSubtitle: {
    color: '#6F6570',
    fontSize: 13,
    marginTop: 6,
    marginBottom: 6,
    lineHeight: 18,
  },
  categoriasCount: {
    color: '#8E7F88',
    fontSize: 12,
    marginBottom: 8,
    fontWeight: '600',
  },
  questionTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#2E2A2E',
    marginBottom: 6,
  },
  stepTwoExtraFields: {
    marginBottom: 8,
  },
  stepTwoFieldCard: {
    paddingHorizontal: 4,
    paddingVertical: 3,
  },
  stepTwoFieldLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.cadCaixaPreferenciasTitulo,
    marginBottom: 8,
    paddingHorizontal: 5,
  },
  stepTwoFieldInput: {
    height: 40,
    borderWidth: 0,
    borderRadius: 8,
    paddingHorizontal: 10,
    color: COLORS.cadCheckboxTexto,
    backgroundColor: 'rgba(255,255,255,0.7)',
  },
  checkboxRow: {
    width: '90%',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    borderRadius: 8,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: COLORS.cadCheckboxFundo,
    backgroundColor: '#FFFFFF',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: COLORS.cadCheckboxFundo,
    borderColor: COLORS.cadCheckboxFundo,
  },
  checkboxMark: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  checkboxText: {
    color: COLORS.cadCheckboxTexto,
    fontSize: 14,
    lineHeight: 20,
    flex: 1,
  },
  checkboxLink: {
    color: COLORS.cadCheckboxLink,
  },
  button: {
    marginTop: 10,
  },
  stepThreeContainer: {
    width: '95%',
    alignItems: 'center',
    flex: 0.95,
  },
  stepThreeTitle: {
    fontFamily: 'SugoDisplay',
    fontSize: 44,
    color: COLORS.cadTitulo,
    marginBottom: 8,
  },
  stepThreeScroll: {
    width: '100%',
  },
  stepThreeContent: {
    alignItems: 'center',
    paddingBottom: 26,
    paddingTop: 6,
  },
  questionBlock: {
    width: '95%',
    borderWidth: 2,
    borderRadius: 18,
    borderColor: COLORS.questionarioCaixaBorda,
    backgroundColor: COLORS.questionarioCaixaFundo,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 12,
    shadowColor: COLORS.questionarioCaixaSombra,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  questionTitle: {
    color: COLORS.questionarioCaixaTexto,
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 10,
  },
  stepThreeInput: {
    width: '100%',
    height: 44,
    backgroundColor: COLORS.questionarioTextInputFundo,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.questionarioTextInputBorda,
    paddingHorizontal: 12,
    color: COLORS.questionarioTextInputTexto,
  },
  optionsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  optionPill: {
    borderWidth: 1,
    borderColor: COLORS.questionarioOpcaoBorda,
    borderRadius: 999,
    backgroundColor: COLORS.questionarioOpcaoFundo,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  optionPillSelected: {
    backgroundColor: COLORS.questionarioOpcaoFundoSelecionada,
    borderColor: COLORS.questionarioOpcaoBordaSelecionada,
  },
  optionText: {
    color: COLORS.questionarioOpcaoTexto,
    fontSize: 14,
    fontWeight: '600',
  },
  optionTextSelected: {
    color: COLORS.questionarioOpcaoTextoSelecionada,
  },
  stepThreeButton: {
    marginTop: 8,
    marginBottom: 8,
  },
  pressableFecharModal: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    padding: 20,
  },
  modalContainer: {
    backgroundColor: COLORS.cadModalContainerFundo,
    borderRadius: 12,
    padding: 16,
    maxHeight: '75%',
  },
  viewModalCarregando: {
    paddingVertical: 24,
    alignItems: 'center',
  },
  textoFecharModalTouchable: {
    marginTop: 12,
    alignItems: 'center',
    paddingVertical: 10,
  },
  textoFecharModal: {
    color: COLORS.cadModalFecharTexto,
    fontWeight: '600',
  },
  categoriaNomeTouchable: {
    paddingVertical: 14,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(46,42,46,0.06)',
  },
  categoriaNome: {
    color: '#2E2A2E',
    fontWeight: '450',
    fontSize: 14,
  },
  avisoNenhumaCategoria: {
    paddingVertical: 16,
    color: COLORS.cadModalAvisoTexto,
  }
});
