import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: COLORS.fundoPrincipal,
    paddingHorizontal: 14,
    paddingVertical: 25,
  },
  heroCard: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 18,
    borderRadius: 18,
    marginBottom: 10,
  },
  logo: {
    width: 120,
    height: 120,
    marginBottom: 4,
  },
  titleRow: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 4,
  },
  badge: {
    color: COLORS.cadTextoAdicionarLimites,
    backgroundColor: 'rgba(239,89,109,0.08)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  titulo: {
    fontFamily: 'SugoDisplay',
    fontSize: 38,
    lineHeight: 40,
    color: COLORS.cadTitulo,
    textAlign: 'center',
    marginBottom: 6,
  },
  subtitle: {
    color: '#6F6570',
    fontSize: 12.5,
    lineHeight: 18,
    textAlign: 'center',
    paddingHorizontal: 12,
  },
  segmentAction: {
    marginTop: 8,
    marginBottom: 14,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.6)',
  },
  segmentActionText: {
    color: COLORS.cadTextoAdicionarLimites,
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  checkboxRow: {
    width: '90%',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  checkbox: {
    width: 14,
    height: 14,
    borderRadius: 1,
    backgroundColor: COLORS.cadCheckboxFundo,
    marginRight: 10,
  },
  checkboxText: {
    color: COLORS.cadCheckboxTexto,
  },
  checkboxLink: {
    color: COLORS.cadCheckboxLink,
  },
  button: {
    marginTop: 15,
  },
  actionsArea: {
    width: '100%',
    alignItems: 'center',
    paddingTop: 6,
    paddingHorizontal: 30,
    paddingBottom: 6,
  },
  stepThreeContainer: {
    width: '95%',
    alignItems: 'center',
    flex: 0.95,
  },
  stepThreeTitle: {
    fontFamily: 'SugoDisplay',
    fontSize: 44,
    color: COLORS.cadTitulo,
    marginBottom: 8,
  },
  stepThreeScroll: {
    width: '100%',
  },
  stepThreeContent: {
    alignItems: 'center',
    paddingTop: 6,
    paddingBottom: 26,
  },
  questionBlock: {
    width: '95%',
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderRadius: 12,
    borderColor: COLORS.cadCaixaPreferenciasBorda,
  },
  questionTitle: {
    color: COLORS.cadCaixaPreferenciasTitulo,
    fontSize: 15.5,
    fontWeight: '800',
    marginBottom: 8,
  },
  stepThreeInput: {
    width: '100%',
    height: 44,
    backgroundColor: COLORS.cadTextInputFundo,
    borderRadius: 12,
    paddingHorizontal: 12,
    color: COLORS.cadTextInputTexto,
  },
  optionsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  optionPill: {
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  optionPillSelected: {
    backgroundColor: COLORS.cadCheckboxFundo,
  },
  optionText: {
    color: COLORS.cadCaixaPreferenciasTitulo,
    fontSize: 12.5,
    fontWeight: '600',
  },
  optionTextSelected: {
    color: '#FFFFFF',
  },
  stepThreeButton: {
    marginTop: 6,
    marginBottom: 8,
    width: '100%',
  },
  secondaryAction: {
    paddingVertical: 5,
    paddingHorizontal: 14,
  },
  secondaryActionText: {
    color: COLORS.cadTextoAdicionarLimites,
    fontSize: 13.5,
    fontWeight: '700',
    textAlign: 'center',
  },
  closeButton: {
    position: 'absolute',
    top: 18,
    right: 18,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 20,
    backgroundColor: 'rgba(255,255,255,0.72)',
  },
  closeText: {
    fontSize: 22,
    color: COLORS.cadCaixaPreferenciasTitulo,
    fontWeight: '700',
  },
  skipButton: {
    position: 'absolute',
    top: 18,
    right: 16,
    zIndex: 20,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.72)',
  },
  skipButtonText: {
    color: COLORS.cadCaixaPreferenciasTitulo,
    fontSize: 13,
    fontWeight: '700',
  },
  pressableFecharModal: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.24)',
    justifyContent: 'center',
    padding: 18,
  },
  modalContainer: {
    backgroundColor: COLORS.cadModalContainerFundo,
    borderRadius: 16,
    padding: 16,
    maxHeight: '75%',
  },
  viewModalCarregando: {
    paddingVertical: 24,
    alignItems: 'center',
  },
  textoFecharModalTouchable: {
    marginTop: 10,
    alignItems: 'center',
    paddingVertical: 10,
  },
  textoFecharModal: {
    color: COLORS.cadModalFecharTexto,
    fontWeight: '700',
  },
  categoriaNomeTouchable: {
    paddingVertical: 12,
    paddingHorizontal: 6,
  },
  categoriaNome: {
    color: COLORS.cadModalItemTexto,
    fontWeight: '500',
    fontSize: 14,
  },
  avisoNenhumaCategoria: {
    paddingVertical: 16,
    color: COLORS.cadModalAvisoTexto,
  },
});
